language: node_js

before_install:
    - npm install juttle@0.7.x

node_js:
    - '4.2'
    - '5.0'

before_script:
    - npm install -g eslint

script:
    - npm test
    - npm run -s check-coverage
